name: EditorConfig

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
    - run: editorconfig-checker
